services:

  app:
    container_name: "webtrees"
    build:
      context: .
    ports:
      - "2015:2015"
    volumes:
      - ./data/webtrees:/srv/webtrees/data
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: "webtrees-db"
    image: mariadb:10.4
    volumes:
      - ./data/webtrees-db:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./data/secrets/mariadb.env

networks:
  backend:
