name: Build and Release Images

on:
  push:
    branches:
      - main
    paths:
      - .arg
  workflow_dispatch:
    inputs:
      push:
        description: Push image to registries
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Images
        run: earthly --ci +docker

      - name: Push to Docker Hub
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true')
        run: earthly --ci --push +docker

      - name: Push to GitHub Container Registry
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true')
        run: earthly --ci --push +docker --REGISTRY=ghcr.io
